### ISSUE TITLE
Boolean optimizations

### ISSUE THREAD

**Issue by npupko** [Set27/lessons#3]
https://github.com/Set27/lessons/blob/3bf505b5962c64fd74eb6658573cc740da23b463/isPrime/isPrime.rb#L31-L35

How could we optimize this part of code consider we already have boolean value inside `truefalse` variable?

**Comment by Set27** [comment]
if

**Comment by Set27** [comment]
`if truefalse
puts truetfalse
else
puts truefalse`

is it better?

**Comment by npupko** [comment]
@Set27 But our parts for `true` and `false` conditions are the same. Do we need `if` at all if we returning the same value regardless of condition?

**Comment by Set27** [comment]
Just `puts truefalse` ?
